# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: bioc-release
sudo: false
cache: packages

addons:
       apt:
         update: true
         sources:
           - sourceline: 'ppa:opencpu/imagemagick'
         packages:
           - libmagick++-dev

branches:
  only:
    - master
    
after_success:
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'lintr::lint_package()'
